apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sample-role
subjects:
  - kind: ServiceAccount
    name: ss
    namespace: default
