apiVersion: v1
kind: Service
metadata:
  name:  demo
  labels:
    app: demo
spec:
  selector:
    app:  demo
  type:  ClusterIP
  ports:
    - port:  8888
      protocol: TCP
      targetPort:  8888
