apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: po3rin/hello:latest
        ports:
          - containerPort: 3000
        resources:
            limits:
              memory: "20Mi"
              cpu: "250m"
        # env:
        #   - name: BLOG_API_ENV
        #     value: {{ .Values.env.apiEnv }}
        #   - name: BLOG_LOG_LEVEL
        #     value: {{ .Values.env.logLevel }}
        #   - name: BLOG_GRPC_URL
        #     value: {{ .Values.env.grpcURL }}
        livenessProbe:
            httpGet:
              port: 3000
              path: /
            failureThreshold: 5
            periodSeconds: 5
